#!/bin/sh

DOCKER_RUN="docker run --rm --tty --interactive --volume $(pwd):/code --workdir /code --publish 1234:1234 node:12"

$DOCKER_RUN yarn install
$DOCKER_RUN yarn icons
$DOCKER_RUN yarn sprites
$DOCKER_RUN yarn run dev
