name: trigger deployment to production
on:
  push:
  workflow_dispatch:
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: trigger GitLab job
        uses: appleboy/gitlab-ci-action@v0.0.2
        with:
          host: https://gitlab.makina-corpus.net
          token: ${{ secrets.TOKEN }}
          ref: master
          project_id: ${{ secrets.PROJECT_ID }}
